export const styles = {
  root: {
    height: "650px",
    position: "relative",
    overflow: "hidden",
  },
  wrapper: {
    flexDirection: "column",
    background: "url(/images/404-background.jpg)",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "end",
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "start",
    justifyContent: "start",
  },
  title: {
    margin: "30px 0 0 40px",
    width: "100%",
    fontFamily: "Montserrat Alternates",
    fontSize: "90px",
    color: "#FFFFFF",
  },
  subTitle: {
    fontFamily: "Montserrat Alternates",
    width: "100%",
    margin: "30px 0 0 40px",
    fontSize: "50px",
    lineHeight: "30px",
    color: "#FFFFFF",
  },
  button: {
    width: "100%",
    margin: "60px 0 0 40px",
    color: "#FFFFFF",
    border: "1px solid #FFFFFF",
    borderRadius: "8px",
    minWidth: "360px",
  },
  nextLink: { textDecoration: "none", color: "#FFFFFF" },
} as any;
